---

# This is the string configuration file for English.
en-GB:
  # Terrain space
  terrain_name_teleporter: Teleporter
  # Teleport Verb
  ui_unit_verbs_teleport: Teleport

  codex_terrain_teleporter_desert_description_text: Cherrystone teleporers shine like a beacon in the sun. Its surface is adorned with a magical cherrystone.
  codex_terrain_teleporter_grass_description_text: A teleporter built by Cherrystone's ancestral mages to encourage trade in times of peace and to save the innocent in times of need.
  codex_terrain_teleporter_ice_description_text: A teleporter built against the snowy wastes. It vibrates with warmth to comfort weary travelers.
  codex_terrain_teleporter_stats_text: Stone teleporters allow easy access to the front lines, but leave units vulnerable.
  codex_terrain_teleporter_strategy_text: Teleporters give strong-but-slow units like ballistas, trebuchets and pikeman immediate access to the front lines. Teleporters do not defend you if you drop into enemy territory, so be careful when warping to teleporters in enemy territory.
  terrain_description_teleporter: Teleporters allow easy access to the front lines, but leave units on them vulnerable.

...